apiVersion: v1
kind: Service
metadata:
  name: express-srv
spec:
  type: NodePort
  selector:
    app: express
  ports:
    - name: express
      protocol: TCP
      port: 3000
      targetPort: 3000
