apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
        - name: express
          image: oxyrus/expressdocker:latest
